apiVersion: v1
kind: Secret
metadata:
  name: payment
  namespace: mechanoidstore
data:
  AMQP_USER: cm9ib3Nob3A=
  AMQP_PASS: cm9ib3Nob3AxMjM=
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: mechanoidstore
  labels:
    app:  payment
    project: mechanoidstore
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  payment
      project: mechanoidstore
      tier: app
  template:
    metadata:
      labels:
        app:  payment
        project: mechanoidstore
        tier: app
    spec:
      containers:
      - name: payment
        image: jashwanth5668/payment:v1
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name:  payment
---
apiVersion: v1
kind: Service
metadata:
  name:  payment
  namespace: mechanoidstore
spec:
  selector:
    app:  payment
    project: mechanoidstore
    tier: app
  ports:
  - protocol:  TCP
    port:  8080
    targetPort:  8080