apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: mechanoidstore
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  cart
  namespace: mechanoidstore
  labels: #these labels are deployment labels
    app:  cart
    project: mechanoidstore
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
      app:  cart
      project: mechanoidstore
      tier: app
  template:
    metadata:
      labels: #these are pod labels
        app:  cart
        project: mechanoidstore
        tier: app
    spec:
      containers:
      - name: cart
        image:  jashwanth5668/cart:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name:  cart
---
apiVersion: v1
kind: Service
metadata:
  name:  cart
  namespace: mechanoidstore
spec:
  selector:
    app:  cart
    project: mechanoidstore
    tier: app
  ports:
  - protocol: TCP
    port:  8080 #service port
    targetPort: 8080 #container port