apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: mechanoidstore
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  shipping
  namespace: mechanoidstore
  labels: #these labels are deployment labels
    app:  shipping
    project: mechanoidstore
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
      app:  shipping
      project: mechanoidstore
      tier: app
  template:
    metadata:
      labels: #these are pod labels
        app:  shipping
        project: mechanoidstore
        tier: app
    spec:
      containers:
      - name: shipping
        image:  jashwanth5668/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name:  shipping
---
apiVersion: v1
kind: Service
metadata:
  name:  shipping
  namespace: mechanoidstore
spec:
  selector:
    app:  shipping
    project: mechanoidstore
    tier: app
  ports:
  - protocol: TCP
    port:  8080 #service port
    targetPort: 8080 #container port