apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: mechanoidstore
data:
  RABBITMQ_DEFAULT_USER: cm9ib3Nob3A=
  RABBITMQ_DEFAULT_PASS: cm9ib3Nob3AxMjM=
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: mechanoidstore
  labels:
    app:  rabbitmq
    project: mechanoidstore
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  rabbitmq
      project: mechanoidstore
      tier: db
  template:
    metadata:
      labels:
        app:  rabbitmq
        project: mechanoidstore
        tier: db
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name:  rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name:  rabbitmq
  namespace: mechanoidstore
spec:
  selector:
    app:  rabbitmq
    project: mechanoidstore
    tier: db
  ports:
  - protocol:  TCP
    port:  5672
    targetPort:  5672