apiVersion: apps/v1
kind: Deployment
metadata:
  name:  mongodb
  namespace: mechanoidstore
  labels: #these labels are deployment labels
    app:  mongodb
    project: mechanoidstore
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels: #these labels are used to find the pods
      app:  mongodb
      project: mechanoidstore
      tier: db
  template:
    metadata:
      labels: #these are pod labels
        app:  mongodb
        project: mechanoidstore
        tier: db
    spec:
      containers:
        - name: mongodb
          image:  jashwanth5668/mongodb:v1
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name:  mongodb
  namespace: mechanoidstore
spec:
  selector:
    app:  mongodb
    project: mechanoidstore
    tier: db
  ports:
  - protocol: TCP
    port:  27017 #service port
    targetPort: 27017 #container port