apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mechanoidstore
data:
  MYSQL_DATABASE: "cities"
---
apiVersion: v1
kind: Secret
metadata:
  name:  mysql
  namespace: mechanoidstore
data:
  MYSQL_ROOT_PASSWORD: Um9ib1Nob3BAMQ==
  MYSQL_USER: c2hpcHBpbmc=
  MYSQL_PASSWORD: Um9ib1Nob3BAMQ==
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mechanoidstore
  labels:
    app:  mysql
    project: mechanoidstore
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  mysql
      project: mechanoidstore
      tier: db
  template:
    metadata:
      labels:
        app:  mysql
        project: mechanoidstore
        tier: db
    spec:
      containers:
      - name: mysql
        image: jashwanth5668/mysql:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name:  mysql
        - secretRef:
            name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name:  mysql
  namespace: mechanoidstore
spec:
  selector:
    app:  mysql
    project: mechanoidstore
    tier: db
  ports:
  - protocol: TCP
    port:  3306
    targetPort:  3306